"""Narrow repository protocols for GAIA OS persistence."""

from typing import Protocol

from gaia.domain.context import ContextPacket
from gaia.domain.entities import Decision, Idea, Note, Project, Task
from gaia.domain.events import Event
from gaia.domain.state import CurrentState


class ProjectRepository(Protocol):
    """Narrow persistence protocol for Projects."""

    async def create_project(self, project: Project) -> Project: ...
    async def get_project(self, project_id: str) -> Project | None: ...
    async def list_projects(self, status: str | None = None) -> list[Project]: ...


class TaskRepository(Protocol):
    """Narrow persistence protocol for Tasks."""

    async def create_task(self, task: Task) -> Task: ...
    async def get_task(self, task_id: str) -> Task | None: ...
    async def list_tasks(
        self, project_id: str | None = None, status: str | None = None
    ) -> list[Task]: ...


class IdeaRepository(Protocol):
    """Narrow persistence protocol for Ideas."""

    async def create_idea(self, idea: Idea) -> Idea: ...
    async def get_idea(self, idea_id: str) -> Idea | None: ...
    async def list_ideas(self, project_id: str | None = None) -> list[Idea]: ...


class NoteRepository(Protocol):
    """Narrow persistence protocol for Notes."""

    async def create_note(self, note: Note) -> Note: ...
    async def get_note(self, note_id: str) -> Note | None: ...
    async def list_notes(self, project_id: str | None = None) -> list[Note]: ...


class DecisionRepository(Protocol):
    """Narrow persistence protocol for Decisions."""

    async def create_decision(self, decision: Decision) -> Decision: ...
    async def get_decision(self, decision_id: str) -> Decision | None: ...
    async def list_decisions(self, project_id: str | None = None) -> list[Decision]: ...


class StateRepository(Protocol):
    """Narrow persistence protocol for CurrentState and ContextPackets."""

    async def get_current_state(self) -> CurrentState: ...
    async def update_current_state(self, state: CurrentState) -> CurrentState: ...
    async def append_context_packet(self, packet: ContextPacket) -> ContextPacket: ...
    async def get_recent_context_packets(self, limit: int = 10) -> list[ContextPacket]: ...


class EventRepository(Protocol):
    """Narrow persistence protocol for append-only Event logging."""

    async def append_event(self, event: Event) -> Event: ...
    async def get_events(
        self, correlation_id: str | None = None, limit: int = 100
    ) -> list[Event]: ...
